
language: android
dist: trusty
android:
  components:
  - build-tools-29.0.2
  - android-29

script:
- chmod +x gradlew
- ./gradlew buildlanguage: android
dist: trusty
jdk: oraclejdk8
android:
 components:
          - tools
          - android-29
          - build-tools-29.0.2
      script:
        - ./gradlew test
       

